### ISSUE TITLE
Is there a split size can be set to a number of objects?

### ISSUE THREAD

**Issue by eyelove** [Gild/bson-splitter#2]
Thank you for letting me provide a very necessary tool.

If you can set the split method as non-capacity object like you will write more useful number.
Is there a can provide this functionality?

**Comment by jfelectron** [comment]
@eyelove check out https://github.com/taganaka/bson-splitter-c . Its faster than the Java version and has a command line parameter to specify split size.

**Comment by jfelectron** [comment]
@taganaka wrote both of them btw :)

**Comment by taganaka** [comment]
@eyelove Not sure if I got your question right. Do you want to split a BSON file by number of documents rather than of a fixed size?

It is not supported but you can do some preemptive math on your collection and estimate the output size based on the number of documents:

```
> db.test.stats()
{
	"ns" : "test.test",
	"count" : 131551,
	"size" : 567996928,
	"avgObjSize" : 4317,
	"storageSize" : 629637120,
	"numExtents" : 16,
	"nindexes" : 1,
	"lastExtentSize" : 168742912,
	"paddingFactor" : 1,
	"systemFlags" : 1,
	"userFlags" : 1,
	"totalIndexSize" : 6099296,
	"indexSizes" : {
		"_id_" : 6099296
	},
	"ok" : 1
}
```
The average object size is ___4317___

Let's assume you want ~10000 doc for each split:
```4317 * 10000 / 1024 / 1024 ~= 41```

And then execute:
```
./bin/bson-splitter dump/test/test.bson /tmp/split 41 'split-%d.bson'
```

Assuming your documents are all similar in size and equally distributed, you should end by having several files containing on average 10k of documents 

Hope this help

**Comment by eyelove** [comment]
@taganaka @jfelectron  thanks :+1:
